version: '3'

services:
  php:
    image: php
    environment:
      APP_DEBUG: "true"
      APP_KEY: "base64:7m52bDzgCHH+WZ/djiXfX0tfw7Lq4SkO46TuJJUW68I="
    build: 
      context: .
    volumes:
      - ./:/var/www/html
    networks:
          - laravel_network

  web:
    image: nginx:1.27
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
          - laravel_network

  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
          - laravel_network

  node:
    image: node
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run dev
    networks:
      - laravel_network


  redis:
    image: redis
    volumes:
      - redisdata:/data
    networks:
          - laravel_network

volumes:
  mysqldata:
  redisdata:

networks:
  laravel_network: